version: "3.4"

services:
  resurface:
    image: docker.resurface.io/release/resurface:3.0.34
    container_name: resurface
    ports:
      - 7700:7700
      - 7701:7701
  
  sniffer:
    image: docker.resurface.io/release/network-sniffer:1.0.1
    container_name: resurface-sniffer
    network_mode: "host"
    env_file: ./src/.env
