version: "3.8"

services:
  resurface:
    image: resurfaceio/resurface:3.2.6
    container_name: resurface
    ports:
      - 7700:7700
      - 7701:7701
    deploy:
      resources:
        reservations:
          cpus: '2'
          memory: 6G
        limits:
          cpus: '4'
          memory: 8G
  
  sniffer:
    image: network-sniffer
    container_name: resurface-sniffer
    network_mode: "host"
    env_file: .env
