version: "3.8"

services:
  resurface:
    image: resurfaceio/resurface:3.5.36
    container_name: resurface
    ports:
      - 7700:7700
      - 7701:7701
    deploy:
      resources:
        reservations:
          cpus: '4'
          memory: 8G
        limits:
          cpus: '6'
          memory: 10G
  
  httpbin:
    image: kennethreitz/httpbin
    container_name: httpbin
    ports:
      - 80:80
  
  sniffer:
    image: resurfaceio/network-sniffer:1.4.0
    container_name: resurface-sniffer
    network_mode: "host"
    env_file: .env

