version: "3.4"

services:
  resurface:
    image: resurfaceio/resurface:2.3.1
    container_name: resurface
    ports:
      - 4000:4000
      - 4001:4001
      - 4002:4002
  
  goreplay:
    image: goreplay:resurface
    container_name: goreplay
    network_mode: "host"
    env_file: ./src/.env
