version: "3.8"

services:
  resurface:
    image: resurfaceio/resurface:3.2.6
    container_name: resurface
    ports:
      - 7700:7700
      - 7701:7701
    deploy:
      resources:
        reservations:
          cpus: '2'
          memory: 6G
        limits:
          cpus: '4'
          memory: 8G
  
  httpbin:
    image: kennethreitz/httpbin
    container_name: httpbin
    ports:
      - 80:80
  
  sniffer:
    image: resurfaceio/network-sniffer:1.2.3
    container_name: resurface-sniffer
    network_mode: "host"
    env_file: .env
    profiles:
      - default

  sniffer-debug:
    image: resurfaceio/network-sniffer:1.2.3-debug
    container_name: resurface-sniffer
    network_mode: "host"
    env_file: .env
    profiles:
      - debug